name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    outputs: 
        semver: ${{ steps.semver.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis
          
      - name: Application Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true

      - name: Build
        run: dotnet build

      - name: Run unit tests
        run: dotnet test
    
  delivery:
    runs-on: ubuntu-latest
    needs: integration
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis
          
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build and Push Docker image (web)
        run: |
          docker build \
            -t ghcr.io/tboulund-dls/calculator-web:${{ needs.integration.outputs.semver }} \
            -f Web/Dockerfile \
            .
          docker push ghcr.io/tboulund-dls/calculator-web --all-tags

      # Build the Docker image
      - name: Build and Push Docker image (API)
        run: |
          docker build \
            -t ghcr.io/tboulund-dls/calculator-api:${{ needs.integration.outputs.semver }} \
            -f API/Dockerfile \
            .
          docker push ghcr.io/tboulund-dls/calculator-api --all-tags